import type { FlaggedDeal, ComplianceRule, AuditLogEntry, ComplianceScoreData, ComplianceMetrics } from './types';

// ═══════════════════════════════════════════════════════════════════════════
// MOCK DATA
// ═══════════════════════════════════════════════════════════════════════════

export const mockFlaggedDeals: FlaggedDeal[] = [
  {
    id: '1',
    dealId: 'NIL-2026-0847',
    athleteName: 'Jordan Davis',
    athleteId: '3',
    brandName: 'Nike',
    brandId: '1',
    dealAmount: 125000,
    dealType: 'Multi-Year Endorsement',
    flagReason: 'Deal value ($125,000) exceeds single-season compensation cap of $100,000 for football athletes under Big 12 Conference guidelines',
    severity: 'high',
    assignedReviewer: 'Dr. Michael Chen (AD)',
    createdAt: '2026-02-12T14:23:00Z',
    status: 'pending',
  },
  {
    id: '2',
    dealId: 'NIL-2026-0851',
    athleteName: 'Marcus Johnson',
    athleteId: '1',
    brandName: 'DraftKings',
    brandId: '8',
    dealAmount: 45000,
    dealType: 'Brand Ambassador',
    flagReason: 'Sports betting companies are restricted under university NIL policy. Requires Athletic Director and General Counsel review.',
    severity: 'high',
    assignedReviewer: null,
    createdAt: '2026-02-12T10:15:00Z',
    status: 'pending',
  },
  {
    id: '3',
    dealId: 'NIL-2026-0839',
    athleteName: 'Emma Chen',
    athleteId: '4',
    brandName: 'Topps Trading Cards',
    brandId: '5',
    dealAmount: 12500,
    dealType: 'Autograph Session Series',
    flagReason: 'Missing required tax documentation: W-9 form not submitted. IRS compliance requirement.',
    severity: 'medium',
    assignedReviewer: 'Sarah Martinez (Compliance)',
    createdAt: '2026-02-11T16:45:00Z',
    status: 'pending',
  },
  {
    id: '4',
    dealId: 'NIL-2026-0832',
    athleteName: 'Tyler Brooks',
    athleteId: '5',
    brandName: 'Gatorade',
    brandId: '2',
    dealAmount: 8500,
    dealType: 'Social Media Campaign',
    flagReason: 'FTC disclosure violation: Instagram posts missing required #ad or #sponsored hashtags. 3 posts identified.',
    severity: 'low',
    assignedReviewer: 'James Wilson (Digital Media)',
    createdAt: '2026-02-10T09:30:00Z',
    status: 'investigating',
  },
  {
    id: '5',
    dealId: 'NIL-2026-0828',
    athleteName: 'Mia Rodriguez',
    athleteId: '6',
    brandName: 'Tesla Motors',
    brandId: '9',
    dealAmount: 35000,
    dealType: 'Product Placement',
    flagReason: 'Automotive category requires additional insurance verification and liability waiver per Risk Management.',
    severity: 'medium',
    assignedReviewer: 'Dr. Michael Chen (AD)',
    createdAt: '2026-02-09T11:20:00Z',
    status: 'investigating',
  },
  {
    id: '6',
    dealId: 'NIL-2026-0815',
    athleteName: 'DeShawn Williams',
    athleteId: '7',
    brandName: 'Beats by Dre',
    brandId: '10',
    dealAmount: 75000,
    dealType: 'Equipment Endorsement',
    flagReason: 'Potential conflict with existing university equipment contract with Bose. Legal review required.',
    severity: 'high',
    assignedReviewer: 'Lisa Park (General Counsel)',
    createdAt: '2026-02-08T14:00:00Z',
    status: 'pending',
  },
  {
    id: '7',
    dealId: 'NIL-2026-0798',
    athleteName: 'Sarah Williams',
    athleteId: '2',
    brandName: 'Celsius Energy',
    brandId: '7',
    dealAmount: 28000,
    dealType: 'Product Endorsement',
    flagReason: 'Energy drink category flagged for review. University policy requires health advisory review for caffeinated products.',
    severity: 'medium',
    assignedReviewer: 'Sarah Martinez (Compliance)',
    createdAt: '2026-02-07T10:00:00Z',
    status: 'rejected',
  },
  {
    id: '8',
    dealId: 'NIL-2026-0785',
    athleteName: 'Andre Washington',
    athleteId: '8',
    brandName: 'State Farm Insurance',
    brandId: '11',
    dealAmount: 18500,
    dealType: 'Commercial Appearance',
    flagReason: 'Standard review: First NIL deal for freshman athlete. Academic eligibility verification required.',
    severity: 'low',
    assignedReviewer: 'Dr. Michael Chen (AD)',
    createdAt: '2026-02-06T15:30:00Z',
    status: 'approved',
  },
  {
    id: '9',
    dealId: 'NIL-2026-0772',
    athleteName: 'Zoe Thompson',
    athleteId: '9',
    brandName: 'Adidas',
    brandId: '12',
    dealAmount: 42000,
    dealType: 'Apparel Partnership',
    flagReason: 'Cleared after Nike exclusivity waiver received. No conflicts with university athletic contracts.',
    severity: 'low',
    assignedReviewer: 'James Wilson (Digital Media)',
    createdAt: '2026-02-05T09:15:00Z',
    status: 'approved',
  },
];

export const mockComplianceRules: ComplianceRule[] = [
  // Compensation Limits
  {
    id: '1',
    name: 'Single-Season Cap - Football',
    description: 'Maximum total NIL compensation per season for football athletes (Big 12 guideline)',
    category: 'Compensation Limits',
    enabled: true,
    threshold: 100000,
    unit: 'USD',
  },
  {
    id: '2',
    name: 'Single-Season Cap - Basketball',
    description: 'Maximum total NIL compensation per season for basketball athletes',
    category: 'Compensation Limits',
    enabled: true,
    threshold: 85000,
    unit: 'USD',
  },
  {
    id: '3',
    name: 'Single-Season Cap - Olympic Sports',
    description: 'Maximum total NIL compensation per season for Olympic sport athletes',
    category: 'Compensation Limits',
    enabled: true,
    threshold: 50000,
    unit: 'USD',
  },
  {
    id: '4',
    name: 'Individual Deal Cap',
    description: 'Maximum value for a single NIL deal (requires AD approval above this amount)',
    category: 'Compensation Limits',
    enabled: true,
    threshold: 25000,
    unit: 'USD',
  },
  // Restricted Categories
  {
    id: '5',
    name: 'Alcohol & Tobacco',
    description: 'Block all deals with alcohol, tobacco, and vaping companies (NCAA required)',
    category: 'Restricted Categories',
    enabled: true,
  },
  {
    id: '6',
    name: 'Sports Betting & Gambling',
    description: 'Block deals with sportsbooks, casinos, and gambling platforms (Conference required)',
    category: 'Restricted Categories',
    enabled: true,
  },
  {
    id: '7',
    name: 'Adult Entertainment',
    description: 'Block deals with adult entertainment and dating services',
    category: 'Restricted Categories',
    enabled: true,
  },
  {
    id: '8',
    name: 'Cannabis & CBD',
    description: 'Block deals with cannabis dispensaries and CBD product companies',
    category: 'Restricted Categories',
    enabled: true,
  },
  {
    id: '9',
    name: 'Energy Drinks (Review)',
    description: 'Flag energy drink deals for health advisory review (not blocked)',
    category: 'Restricted Categories',
    enabled: true,
  },
  {
    id: '10',
    name: 'Competing Athletic Brands',
    description: 'Flag deals that may conflict with university athletic contracts',
    category: 'Restricted Categories',
    enabled: true,
  },
  // Disclosure Requirements
  {
    id: '11',
    name: 'FTC Social Media Disclosure',
    description: 'Require #ad or #sponsored disclosure on all paid social media posts',
    category: 'Disclosure Requirements',
    enabled: true,
  },
  {
    id: '12',
    name: 'Material Connection Disclosure',
    description: 'Require disclosure of material connection in testimonials and reviews',
    category: 'Disclosure Requirements',
    enabled: true,
  },
  {
    id: '13',
    name: 'University Disclaimer',
    description: 'Require "Not affiliated with [University]" disclaimer in brand content',
    category: 'Disclosure Requirements',
    enabled: false,
  },
  // Documentation Requirements
  {
    id: '14',
    name: 'W-9 Tax Form',
    description: 'Require IRS W-9 form before deal activation (federal requirement)',
    category: 'Documentation',
    enabled: true,
  },
  {
    id: '15',
    name: 'Contract Review',
    description: 'All contracts over $10,000 must be reviewed by university legal counsel',
    category: 'Documentation',
    enabled: true,
  },
  {
    id: '16',
    name: 'Agent Disclosure',
    description: 'Require disclosure of agent/representative information if applicable',
    category: 'Documentation',
    enabled: true,
  },
  {
    id: '17',
    name: 'Insurance Verification',
    description: 'Verify liability insurance for physical appearance and event deals',
    category: 'Documentation',
    enabled: true,
  },
  // Academic Requirements
  {
    id: '18',
    name: 'Minimum GPA',
    description: 'Athletes must maintain minimum GPA for NIL eligibility',
    category: 'Academic Requirements',
    enabled: true,
    threshold: 2.5,
    unit: 'GPA',
  },
  {
    id: '19',
    name: 'Full-Time Enrollment',
    description: 'Athletes must be enrolled full-time (12+ credit hours)',
    category: 'Academic Requirements',
    enabled: true,
    threshold: 12,
    unit: 'credits',
  },
  {
    id: '20',
    name: 'Academic Good Standing',
    description: 'Athletes must not be on academic probation',
    category: 'Academic Requirements',
    enabled: true,
  },
  // Practice & Competition
  {
    id: '21',
    name: 'Practice Conflict Check',
    description: 'NIL activities cannot conflict with scheduled practices or team meetings',
    category: 'Practice & Competition',
    enabled: true,
  },
  {
    id: '22',
    name: 'Game Day Restrictions',
    description: 'No NIL commercial activities within 4 hours of scheduled competitions',
    category: 'Practice & Competition',
    enabled: true,
    threshold: 4,
    unit: 'hours',
  },
  {
    id: '23',
    name: 'Travel Approval',
    description: 'NIL activities requiring travel must be approved by coaching staff',
    category: 'Practice & Competition',
    enabled: false,
  },
];

export const mockAuditLog: AuditLogEntry[] = [
  {
    id: '1',
    timestamp: '2026-02-13T09:45:00Z',
    adminUser: 'Dr. Michael Chen (AD)',
    actionType: 'deal_approved',
    target: 'Andre Washington - State Farm Deal (NIL-2026-0785)',
    details: 'Freshman eligibility verified. Academic standing confirmed at 3.62 GPA. Deal value: $18,500',
  },
  {
    id: '2',
    timestamp: '2026-02-13T08:30:00Z',
    adminUser: 'System',
    actionType: 'flag_raised',
    target: 'Marcus Johnson - DraftKings Deal (NIL-2026-0851)',
    details: 'Auto-flagged: Sports betting category restricted under university NIL policy Section 4.2',
  },
  {
    id: '3',
    timestamp: '2026-02-12T16:20:00Z',
    adminUser: 'Lisa Park (General Counsel)',
    actionType: 'flag_raised',
    target: 'DeShawn Williams - Beats by Dre (NIL-2026-0815)',
    details: 'Potential conflict identified with existing Bose equipment contract. Forwarded to legal review.',
  },
  {
    id: '4',
    timestamp: '2026-02-12T14:23:00Z',
    adminUser: 'System',
    actionType: 'flag_raised',
    target: 'Jordan Davis - Nike Deal (NIL-2026-0847)',
    details: 'Auto-flagged: Deal value ($125,000) exceeds Big 12 single-season cap ($100,000)',
  },
  {
    id: '5',
    timestamp: '2026-02-12T11:00:00Z',
    adminUser: 'Dr. Michael Chen (AD)',
    actionType: 'rule_changed',
    target: 'Single-Season Cap - Football',
    details: 'Threshold updated: $75,000 -> $100,000 per Big 12 Conference guideline update effective Feb 2026',
  },
  {
    id: '6',
    timestamp: '2026-02-11T15:45:00Z',
    adminUser: 'Sarah Martinez (Compliance)',
    actionType: 'athlete_verified',
    target: 'Zoe Thompson',
    details: 'Full verification completed: enrollment (confirmed), sport eligibility (basketball), academic standing (3.75 GPA)',
  },
  {
    id: '7',
    timestamp: '2026-02-10T14:30:00Z',
    adminUser: 'James Wilson (Digital Media)',
    actionType: 'flag_resolved',
    target: 'Tyler Brooks - Gatorade (NIL-2026-0832)',
    details: 'FTC disclosure compliance verified. Athlete added required #ad hashtags to 3 Instagram posts.',
  },
  {
    id: '8',
    timestamp: '2026-02-09T10:15:00Z',
    adminUser: 'System',
    actionType: 'flag_raised',
    target: 'Mia Rodriguez - Tesla Motors (NIL-2026-0828)',
    details: 'Auto-flagged: Automotive category requires additional insurance verification per Risk Management policy',
  },
  {
    id: '9',
    timestamp: '2026-02-08T16:00:00Z',
    adminUser: 'Sarah Martinez (Compliance)',
    actionType: 'deal_rejected',
    target: 'Sarah Williams - Celsius Energy (NIL-2026-0798)',
    details: 'Rejected: Energy drink product failed health advisory review. Contains 300mg caffeine per serving.',
  },
  {
    id: '10',
    timestamp: '2026-02-07T09:30:00Z',
    adminUser: 'Dr. Michael Chen (AD)',
    actionType: 'deal_approved',
    target: 'Zoe Thompson - Adidas Deal (NIL-2026-0772)',
    details: 'Nike exclusivity waiver received and verified. No conflicts with university contracts.',
  },
  {
    id: '11',
    timestamp: '2026-02-06T14:20:00Z',
    adminUser: 'System',
    actionType: 'athlete_verified',
    target: 'Marcus Johnson',
    details: 'Automatic re-verification: Spring semester enrollment confirmed, GPA maintained at 3.87',
  },
  {
    id: '12',
    timestamp: '2026-02-05T11:45:00Z',
    adminUser: 'Sarah Martinez (Compliance)',
    actionType: 'rule_changed',
    target: 'W-9 Tax Form',
    details: 'Rule enabled: All NIL payments now require W-9 on file before disbursement (IRS requirement)',
  },
];

export const mockComplianceScore: ComplianceScoreData = {
  overall: 94,
  previousMonth: 91,
  breakdown: {
    documentation: 98,
    dealCompliance: 92,
    disclosureAdherence: 95,
    academicStanding: 91,
  },
  trends: {
    documentation: { current: 98, previous: 96, trend: 'up' },
    dealCompliance: { current: 92, previous: 94, trend: 'down' },
    disclosureAdherence: { current: 95, previous: 92, trend: 'up' },
    academicStanding: { current: 91, previous: 91, trend: 'stable' },
  },
};

export const mockMetrics: ComplianceMetrics = {
  totalDealsReviewed: 168,
  dealsThisMonth: 23,
  avgResolutionHours: 18.5,
  complianceRate: 94.2,
};
