-- HS-NIL Deal Disputes (Phase 7)
-- ============================================================
-- Either side of a signed deal can raise a dispute — athlete says brand
-- is stalling review, brand says deliverable misrepresented, parent says
-- payment didn't arrive, brand wants to cancel due to athlete misconduct.
-- Disputes pause the deal (and any pending payout) until an admin mediates.
-- Every action is audit-logged via admin_audit_log.
--
-- Scope of this migration:
--   1. Extend deal_status enum with 'disputed'.
--   2. Extend admin_audit_log CHECK constraint to include the four new
--      dispute-action values.
--   3. deal_disputes table + RLS.
-- ============================================================

-- ============================================================
-- 1. Extend deal_status enum
-- ============================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_enum
    WHERE enumlabel = 'disputed'
      AND enumtypid = 'deal_status'::regtype
  ) THEN
    ALTER TYPE deal_status ADD VALUE 'disputed';
  END IF;
END $$;

-- ============================================================
-- 2. Extend admin_audit_log CHECK to include dispute actions
-- ============================================================
--
-- The baseline 20260418_012 migration constrained action to four values.
-- We must drop the existing CHECK and re-create with the union so the
-- DISPUTE-FLOW admin-actions service can write without violating the
-- constraint. The constraint name is auto-generated by Postgres as
-- `admin_audit_log_action_check` — we look it up defensively in case the
-- name diverges across environments.
-- ============================================================

DO $$
DECLARE
  v_constraint_name text;
BEGIN
  SELECT conname INTO v_constraint_name
  FROM pg_constraint
  WHERE conrelid = 'public.admin_audit_log'::regclass
    AND contype = 'c'
    AND pg_get_constraintdef(oid) LIKE '%action%';

  IF v_constraint_name IS NOT NULL THEN
    EXECUTE format(
      'ALTER TABLE public.admin_audit_log DROP CONSTRAINT %I',
      v_constraint_name
    );
  END IF;

  ALTER TABLE public.admin_audit_log
    ADD CONSTRAINT admin_audit_log_action_check
    CHECK (action IN (
      'disclosure_retry',
      'payout_resolve',
      'link_force_verify',
      'consent_renewal_nudge',
      'dispute_raised',
      'dispute_resolved_in_favor_of_athlete',
      'dispute_resolved_in_favor_of_brand',
      'dispute_split'
    ));
END $$;

-- Extend the target_kind CHECK in the same defensive pattern — dispute
-- actions target a dispute row (target_kind='deal' — we store the deal id
-- in target_id and the dispute id in metadata.disputeId so a disputes-free
-- admin can still filter by deal). Add 'deal' to the allowed set.

DO $$
DECLARE
  v_constraint_name text;
BEGIN
  SELECT conname INTO v_constraint_name
  FROM pg_constraint
  WHERE conrelid = 'public.admin_audit_log'::regclass
    AND contype = 'c'
    AND pg_get_constraintdef(oid) LIKE '%target_kind%';

  IF v_constraint_name IS NOT NULL THEN
    EXECUTE format(
      'ALTER TABLE public.admin_audit_log DROP CONSTRAINT %I',
      v_constraint_name
    );
  END IF;

  ALTER TABLE public.admin_audit_log
    ADD CONSTRAINT admin_audit_log_target_kind_check
    CHECK (target_kind IN (
      'disclosure',
      'payout',
      'link',
      'consent',
      'deal'
    ));
END $$;

-- ============================================================
-- 3. deal_disputes
-- ============================================================

CREATE TABLE IF NOT EXISTS public.deal_disputes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  deal_id uuid NOT NULL REFERENCES public.deals(id) ON DELETE CASCADE,
  raised_by_user_id uuid NOT NULL REFERENCES auth.users(id),
  raised_by_role text NOT NULL CHECK (raised_by_role IN ('athlete', 'parent', 'brand')),
  reason_category text NOT NULL CHECK (reason_category IN (
    'non_delivery',
    'quality',
    'timing',
    'compensation',
    'misconduct',
    'other'
  )),
  description text NOT NULL CHECK (char_length(description) >= 30),
  evidence_urls text[] NOT NULL DEFAULT ARRAY[]::text[],
  status text NOT NULL DEFAULT 'open' CHECK (status IN (
    'open',
    'under_review',
    'resolved_athlete',
    'resolved_brand',
    'resolved_split',
    'withdrawn'
  )),
  priority text NOT NULL DEFAULT 'standard' CHECK (priority IN (
    'low',
    'standard',
    'high',
    'urgent'
  )),
  -- Snapshot of the pre-dispute deal status so 'withdraw' can restore it.
  deal_status_before_dispute text,
  resolved_by_user_id uuid REFERENCES auth.users(id),
  resolved_at timestamptz,
  resolution_summary text,
  resolution_action jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Primary queue index: admin loads open + under_review, newest first by
-- priority then age. Partial index on status keeps it small.
CREATE INDEX IF NOT EXISTS idx_deal_disputes_open_queue
  ON public.deal_disputes (created_at DESC)
  WHERE status IN ('open', 'under_review');

CREATE INDEX IF NOT EXISTS idx_deal_disputes_deal
  ON public.deal_disputes (deal_id);

ALTER TABLE public.deal_disputes ENABLE ROW LEVEL SECURITY;

-- -----------------------------------------------------------------
-- SELECT policy: allowed for the deal parties (athlete profile_id,
-- parents linked to that athlete via hs_parent_athlete_links, brand
-- owner) OR any admin.
-- -----------------------------------------------------------------

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'deal_disputes'
      AND policyname = 'deal_disputes_party_or_admin_read'
  ) THEN
    CREATE POLICY deal_disputes_party_or_admin_read ON public.deal_disputes
      FOR SELECT
      USING (
        -- Athlete on the deal.
        deal_id IN (
          SELECT d.id
          FROM public.deals d
          JOIN public.athletes a ON a.id = d.athlete_id
          WHERE a.profile_id = auth.uid()
        )
        -- Brand on the deal.
        OR deal_id IN (
          SELECT d.id
          FROM public.deals d
          JOIN public.brands b ON b.id = d.brand_id
          WHERE b.profile_id = auth.uid()
        )
        -- Parent linked to the athlete on the deal (verified link only).
        OR deal_id IN (
          SELECT d.id
          FROM public.deals d
          JOIN public.athletes a ON a.id = d.athlete_id
          JOIN public.hs_parent_athlete_links l ON l.athlete_user_id = a.profile_id
          JOIN public.hs_parent_profiles pp ON pp.id = l.parent_profile_id
          WHERE pp.user_id = auth.uid()
            AND l.verified_at IS NOT NULL
        )
        -- Admin catch-all.
        OR EXISTS (
          SELECT 1 FROM public.profiles p
          WHERE p.id = auth.uid()
            AND p.role = 'admin'
        )
      );
  END IF;
END $$;

-- No INSERT / UPDATE / DELETE policy — writes flow exclusively through the
-- service-role client in src/lib/hs-nil/disputes.ts. Service role bypasses
-- RLS; ordinary clients (even authenticated ones) cannot touch this table
-- directly, which is the whole point: we need the API layer to enforce
-- role mapping, deal-status transition, and admin_audit_log writes
-- atomically.

COMMENT ON TABLE public.deal_disputes IS
  'Dispute records raised by either side of a signed HS-NIL deal. Insert/update via service-role only; select restricted to deal parties + admins.';

COMMENT ON COLUMN public.deal_disputes.deal_status_before_dispute IS
  'Snapshot of deals.status at the moment the dispute was raised. Used by the ''withdraw'' resolution path to restore the prior status.';

COMMENT ON COLUMN public.deal_disputes.resolution_action IS
  'Informational structured action the admin elected at resolution time (e.g., { refund: true, payout_release: false }). Admin must still take the actual actions via OPS-WRITER''s endpoints; this column is the paper trail, not the trigger.';
