/**
 * HS-NIL PDF — shared layout primitives
 * ----------------------------------------------------------------------------
 * Color palette, typography scale, margins, and the header/footer/brand-mark
 * helpers reused by both the deal report and the brand performance report.
 *
 * All PDFs generated by this module are:
 *   - Letter-sized (8.5 x 11 in). US brands download these; A4 would surprise.
 *   - Portrait.
 *   - Rendered in millimetres (jsPDF's internal unit of choice).
 *   - Dark text on white for print-friendliness. The cyan accent is the
 *     GradeUp primary (#00F0FF), used sparingly for rules and pill labels.
 *   - Footer-stamped on every page with a confidentiality notice so a
 *     brand that forwards the PDF accidentally has a paper trail of intent.
 *
 * Everything in this file is deliberately pure — no Supabase / fetch /
 * env reads. That lets deal-report.ts and performance-report.ts stay
 * server-only utilities with an easy Jest boundary.
 */
import { jsPDF } from 'jspdf';

// ----------------------------------------------------------------------------
// Page + typography constants
// ----------------------------------------------------------------------------

/** 8.5" x 11" = 215.9mm x 279.4mm. We round to jsPDF's 'letter' preset. */
export const PAGE_WIDTH_MM = 215.9;
export const PAGE_HEIGHT_MM = 279.4;

export const MARGINS = {
  top: 18,
  bottom: 22, // extra room for footer
  left: 18,
  right: 18,
} as const;

export const CONTENT_WIDTH = PAGE_WIDTH_MM - MARGINS.left - MARGINS.right;

export const FONTS = {
  display: 26,
  title: 20,
  heading: 14,
  subheading: 11,
  body: 10,
  small: 8.5,
  tiny: 7.5,
} as const;

// ----------------------------------------------------------------------------
// Color palette — tuned for print + screen contrast on white
// ----------------------------------------------------------------------------
//
// Greys are deliberately not pure black — full black on white is harsh in
// print. The cyan accent matches the app's --accent-primary (#00F0FF). On
// white it renders as a vivid rule, not body copy.

export const COLORS = {
  /** Headings and body text. */
  text: [18, 24, 32] as [number, number, number],
  /** Secondary captions, metric labels. */
  textMuted: [100, 110, 120] as [number, number, number],
  /** Table rules, dividers. */
  border: [210, 216, 224] as [number, number, number],
  /** Subtle zebra-striping on tables. */
  zebra: [246, 248, 250] as [number, number, number],
  /** Brand accent — use only for horizontal rules and pill labels. */
  accent: [0, 180, 196] as [number, number, number],
  /** Page background (we don't fill; provided for shaded blocks). */
  bg: [255, 255, 255] as [number, number, number],
} as const;

// ----------------------------------------------------------------------------
// Document bootstrap
// ----------------------------------------------------------------------------

export function newDocument(): jsPDF {
  const doc = new jsPDF({
    unit: 'mm',
    format: 'letter',
    orientation: 'portrait',
    compress: true,
  });
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.text);
  return doc;
}

// ----------------------------------------------------------------------------
// Drawing helpers
// ----------------------------------------------------------------------------

/**
 * Draw a full-width horizontal rule at the given y position. Uses the
 * accent colour by default; pass `muted` to draw a thin grey divider.
 */
export function drawRule(
  doc: jsPDF,
  y: number,
  variant: 'accent' | 'muted' = 'accent',
) {
  if (variant === 'accent') {
    doc.setDrawColor(...COLORS.accent);
    doc.setLineWidth(0.9);
  } else {
    doc.setDrawColor(...COLORS.border);
    doc.setLineWidth(0.3);
  }
  doc.line(MARGINS.left, y, PAGE_WIDTH_MM - MARGINS.right, y);
}

/**
 * GradeUp brand-mark. Text-only for now — an image version is a TODO
 * (needs a vectorised logo asset checked into /public). Rendered at the
 * requested y-coordinate, left-aligned to the content margin.
 */
export function drawBrandMark(doc: jsPDF, y: number) {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(FONTS.subheading);
  doc.setTextColor(...COLORS.text);
  doc.text('GradeUp', MARGINS.left, y);
  doc.setTextColor(...COLORS.accent);
  doc.text('HS', MARGINS.left + 19.5, y);
  doc.setTextColor(...COLORS.text);
}

/**
 * Page header — brand mark on the left, report title on the right.
 * Returns the y-coordinate below the header where body content may begin.
 */
export function drawHeader(doc: jsPDF, titleRight: string): number {
  const y = MARGINS.top;
  drawBrandMark(doc, y);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(FONTS.small);
  doc.setTextColor(...COLORS.textMuted);
  const textWidth = doc.getTextWidth(titleRight);
  doc.text(titleRight, PAGE_WIDTH_MM - MARGINS.right - textWidth, y);

  drawRule(doc, y + 2.5, 'accent');
  doc.setTextColor(...COLORS.text);

  return y + 8;
}

/**
 * Page footer with page number + confidentiality notice. Call this on
 * every page right before emitting the buffer (iterate pages, addPage
 * transitions, etc.). `pageNum` is 1-indexed; `pageTotal` is the final
 * count.
 */
export function drawFooter(
  doc: jsPDF,
  pageNum: number,
  pageTotal: number,
) {
  const y = PAGE_HEIGHT_MM - 12;
  drawRule(doc, y - 4, 'muted');

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(FONTS.tiny);
  doc.setTextColor(...COLORS.textMuted);

  const confidential =
    'GradeUp HS confidential — for brand internal use; do not redistribute.';
  doc.text(confidential, MARGINS.left, y);

  const paging = `Page ${pageNum} of ${pageTotal}`;
  const pagingWidth = doc.getTextWidth(paging);
  doc.text(paging, PAGE_WIDTH_MM - MARGINS.right - pagingWidth, y);

  doc.setTextColor(...COLORS.text);
}

/**
 * Apply drawFooter() to every existing page in the document. Call this
 * immediately before `doc.output(...)` so page totals are accurate.
 */
export function stampFootersOnAllPages(doc: jsPDF) {
  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i += 1) {
    doc.setPage(i);
    drawFooter(doc, i, total);
  }
}

// ----------------------------------------------------------------------------
// Text helpers
// ----------------------------------------------------------------------------

export function setText(
  doc: jsPDF,
  size: number,
  style: 'normal' | 'bold' = 'normal',
  color: readonly [number, number, number] = COLORS.text,
) {
  doc.setFont('helvetica', style);
  doc.setFontSize(size);
  doc.setTextColor(color[0], color[1], color[2]);
}

/**
 * Wrap text to the content width and draw it starting at (x, y). Returns
 * the y-coordinate immediately below the last drawn line. Use this for
 * any multi-line prose — it respects jsPDF's internal line-splitter.
 */
export function drawWrappedText(
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  maxWidth: number = CONTENT_WIDTH,
  lineHeight = 4.8,
): number {
  const lines = doc.splitTextToSize(text, maxWidth) as string[];
  for (const line of lines) {
    doc.text(line, x, y);
    y += lineHeight;
  }
  return y;
}

/**
 * Render a label+value pair in the "ALL CAPS CAPTION / large value"
 * pattern used by the on-screen stat cards. Returns y below the block.
 */
export function drawStatBlock(
  doc: jsPDF,
  label: string,
  value: string,
  x: number,
  y: number,
  options: { valueSize?: number; width?: number; hint?: string } = {},
): number {
  const valueSize = options.valueSize ?? FONTS.title;
  const width = options.width ?? 56;

  setText(doc, FONTS.tiny, 'bold', COLORS.textMuted);
  doc.text(label.toUpperCase(), x, y);

  setText(doc, valueSize, 'bold', COLORS.text);
  doc.text(value, x, y + 7);

  let after = y + 11;
  if (options.hint) {
    setText(doc, FONTS.tiny, 'normal', COLORS.textMuted);
    const hintLines = doc.splitTextToSize(options.hint, width) as string[];
    for (const line of hintLines) {
      doc.text(line, x, after);
      after += 3.6;
    }
  }

  setText(doc, FONTS.body, 'normal', COLORS.text);
  return after;
}

// ----------------------------------------------------------------------------
// Table helpers (used for per-deal summary table)
// ----------------------------------------------------------------------------

export interface TableColumn {
  header: string;
  key: string;
  width: number; // mm
  align?: 'left' | 'right' | 'center';
}

/**
 * Render a simple zebra-striped table. Rows are plain objects keyed by
 * `column.key`. Caller handles pagination by checking the returned y and
 * calling `doc.addPage()` when near `PAGE_HEIGHT_MM - MARGINS.bottom`.
 */
export function drawTable(
  doc: jsPDF,
  columns: TableColumn[],
  rows: Array<Record<string, string>>,
  x: number,
  y: number,
): number {
  const rowH = 6.8;

  // Header
  setText(doc, FONTS.tiny, 'bold', COLORS.textMuted);
  let cx = x;
  for (const col of columns) {
    const tx =
      col.align === 'right'
        ? cx + col.width - 1
        : col.align === 'center'
          ? cx + col.width / 2
          : cx;
    const align = col.align ?? 'left';
    doc.text(col.header.toUpperCase(), tx, y, { align });
    cx += col.width;
  }
  y += 2.5;

  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.3);
  doc.line(x, y, x + columns.reduce((acc, c) => acc + c.width, 0), y);
  y += 4;

  // Rows
  setText(doc, FONTS.small, 'normal', COLORS.text);
  let zebra = false;
  for (const row of rows) {
    if (zebra) {
      doc.setFillColor(...COLORS.zebra);
      doc.rect(
        x,
        y - 4.2,
        columns.reduce((acc, c) => acc + c.width, 0),
        rowH,
        'F',
      );
    }
    let rcx = x;
    for (const col of columns) {
      const value = row[col.key] ?? '—';
      const tx =
        col.align === 'right'
          ? rcx + col.width - 1
          : col.align === 'center'
            ? rcx + col.width / 2
            : rcx;
      const align = col.align ?? 'left';
      // Truncate long strings to the column width so one cell can't
      // bleed into its neighbours.
      const clipped =
        (doc.splitTextToSize(value, col.width - 2) as string[])[0] ?? value;
      doc.text(clipped, tx, y, { align });
      rcx += col.width;
    }
    y += rowH;
    zebra = !zebra;
  }
  return y;
}

// ----------------------------------------------------------------------------
// Misc utilities
// ----------------------------------------------------------------------------

/**
 * URL-safe filename slug. Lowercases, replaces non-alphanumerics with a
 * single dash, trims leading/trailing dashes, and caps at 40 chars so
 * the final filename stays within sensible OS limits.
 */
export function slugify(input: string): string {
  const cleaned = input
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return (cleaned || 'gradeup').slice(0, 40);
}

export function today(): string {
  const d = new Date();
  const y = d.getUTCFullYear();
  const m = String(d.getUTCMonth() + 1).padStart(2, '0');
  const day = String(d.getUTCDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

/**
 * Mask an athlete's surname to a single initial. Required for any PDF
 * output — athletes never appear with a full last name in brand-facing
 * reports.
 */
export function maskAthleteName(
  firstName: string | null | undefined,
  lastName: string | null | undefined,
): string {
  const first = (firstName ?? '').trim() || 'Scholar';
  const last = (lastName ?? '').trim();
  if (!last) return first;
  return `${first} ${last.charAt(0).toUpperCase()}.`;
}

/**
 * Convert jsPDF's ArrayBuffer output to a Node Buffer for streaming back
 * through Next's Response. In a Node runtime both Buffer and Uint8Array
 * are valid body types for NextResponse; we return a Buffer since it's
 * the canonical Node type for binary payloads and lets callers use
 * `.length` directly when setting Content-Length.
 */
export function toBuffer(doc: jsPDF): Buffer {
  const ab = doc.output('arraybuffer') as ArrayBuffer;
  return Buffer.from(ab);
}
