/**
 * Content Security Policy Nonce Utilities
 *
 * This module provides cryptographic nonce generation for CSP headers.
 * Nonces are used to allow specific inline scripts and styles while
 * blocking all others, providing protection against XSS attacks.
 *
 * Usage:
 * 1. Generate a nonce in middleware for each request
 * 2. Pass the nonce to script/style tags via headers
 * 3. Include the nonce in the CSP header
 */

import { headers } from 'next/headers';

/**
 * Header name for storing the CSP nonce
 */
export const CSP_NONCE_HEADER = 'x-csp-nonce';

/**
 * Generate a cryptographically secure nonce for CSP
 * Uses Web Crypto API for secure random generation
 *
 * @returns Base64-encoded 16-byte nonce
 */
export function generateNonce(): string {
  // Generate 16 random bytes (128 bits of entropy)
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);

  // Convert to base64
  return btoa(String.fromCharCode(...bytes));
}

/**
 * Get the CSP nonce from request headers (server-side)
 *
 * This function retrieves the nonce that was generated by the middleware
 * and stored in the request headers. Use this in server components and
 * pages to pass the nonce to scripts.
 *
 * @returns The CSP nonce string or undefined if not found
 */
export async function getNonce(): Promise<string | undefined> {
  const headersList = await headers();
  return headersList.get(CSP_NONCE_HEADER) ?? undefined;
}

/**
 * Build a Content Security Policy header value
 *
 * @param nonce - The cryptographic nonce for this request
 * @param options - Configuration options for the CSP
 * @returns The complete CSP header value
 */
export function buildCspHeader(
  nonce: string,
  options: {
    reportOnly?: boolean;
    reportUri?: string;
  } = {}
): string {
  const directives = [
    // Default policy: only allow same-origin resources
    "default-src 'self'",

    // Script policy: nonce + strict-dynamic. Modern browsers supporting CSP3 will
    // use strict-dynamic and ignore any 'unsafe-inline' fallback (which remains for
    // CSP1/2 browsers only). This closes the XSS gap where 'unsafe-inline' alone
    // silently defeated the nonce plumbing. Next.js scripts that need to execute
    // inline must carry the nonce attribute; any dependent/loaded scripts are
    // allowed transitively via strict-dynamic without needing self/host allowlists.
    `script-src 'self' 'nonce-${nonce}' 'strict-dynamic' 'unsafe-inline' https:`,

    // Style policy: inline styles retained. Tailwind + Next.js emit inline style
    // attributes/tags that are impractical to nonce today, and the XSS-via-style
    // attack surface (CSS exfiltration) is materially lower than script XSS.
    // Revisit if CSP Level 3 style nonce coverage in Next.js improves.
    `style-src 'self' 'unsafe-inline'`,

    // Image policy: allow same-origin, data URIs, and HTTPS images
    "img-src 'self' data: https:",

    // Font policy: allow same-origin and data URIs (for embedded fonts)
    "font-src 'self' data:",

    // Connect policy: allow API connections to required services
    "connect-src 'self' https://*.supabase.co wss://*.supabase.co https://*.sentry.io https://www.google-analytics.com https://analytics.google.com",

    // Frame ancestors: prevent clickjacking
    "frame-ancestors 'none'",

    // Base URI: prevent base tag hijacking
    "base-uri 'self'",

    // Form actions: only allow forms to submit to same origin
    "form-action 'self'",

    // Object policy: block plugins like Flash
    "object-src 'none'",

    // Upgrade insecure requests in production
    "upgrade-insecure-requests",
  ];

  // Add report-uri if provided
  if (options.reportUri) {
    directives.push(`report-uri ${options.reportUri}`);
  }

  return directives.join('; ');
}

/**
 * Build a development-friendly CSP header
 *
 * This CSP is less restrictive to allow for development tools like
 * Hot Module Replacement (HMR), webpack eval, and React DevTools.
 *
 * WARNING: Do not use this in production!
 *
 * @param nonce - The cryptographic nonce for this request
 * @returns The development CSP header value
 */
export function buildDevCspHeader(nonce: string): string {
  const directives = [
    "default-src 'self'",
    // Allow eval for webpack HMR and development tools
    `script-src 'self' 'nonce-${nonce}' 'unsafe-eval'`,
    // Allow unsafe-inline for HMR style injection in development
    `style-src 'self' 'unsafe-inline'`,
    "img-src 'self' data: https: blob:",
    "font-src 'self' data:",
    "connect-src 'self' https://*.supabase.co wss://*.supabase.co https://*.sentry.io https://www.google-analytics.com https://analytics.google.com ws://localhost:* ws://127.0.0.1:*",
    "frame-ancestors 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "object-src 'none'",
  ];

  return directives.join('; ');
}
