/**
 * Content Security Policy Nonce Utilities
 *
 * This module provides cryptographic nonce generation for CSP headers.
 * Nonces are used to allow specific inline scripts and styles while
 * blocking all others, providing protection against XSS attacks.
 *
 * Usage:
 * 1. Generate a nonce in middleware for each request
 * 2. Pass the nonce to script/style tags via headers
 * 3. Include the nonce in the CSP header
 */

import { headers } from 'next/headers';

/**
 * Header name for storing the CSP nonce
 */
// Next.js 13.4+ reads the nonce from an incoming-request header named
// 'x-nonce' and auto-decorates its generated <script> / <style> tags with
// the matching nonce attribute. Using this exact name is load-bearing:
// renaming it (the project previously used 'x-csp-nonce') silently
// defeats Next.js's nonce propagation — inline hydration scripts render
// without the nonce attribute, the CSP then rejects them, and every
// client-component page ships as an empty shell. Do NOT rename.
export const CSP_NONCE_HEADER = 'x-nonce';

/**
 * Generate a cryptographically secure nonce for CSP
 * Uses Web Crypto API for secure random generation
 *
 * @returns Base64-encoded 16-byte nonce
 */
export function generateNonce(): string {
  // Generate 16 random bytes (128 bits of entropy)
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);

  // Convert to base64
  return btoa(String.fromCharCode(...bytes));
}

/**
 * Get the CSP nonce from request headers (server-side)
 *
 * This function retrieves the nonce that was generated by the middleware
 * and stored in the request headers. Use this in server components and
 * pages to pass the nonce to scripts.
 *
 * @returns The CSP nonce string or undefined if not found
 */
export async function getNonce(): Promise<string | undefined> {
  const headersList = await headers();
  return headersList.get(CSP_NONCE_HEADER) ?? undefined;
}

/**
 * Build a Content Security Policy header value
 *
 * @param nonce - The cryptographic nonce for this request
 * @param options - Configuration options for the CSP
 * @returns The complete CSP header value
 */
export function buildCspHeader(
  nonce: string,
  options: {
    reportOnly?: boolean;
    reportUri?: string;
  } = {}
): string {
  const directives = [
    // Default policy: only allow same-origin resources
    "default-src 'self'",

    // Script policy.
    //
    // HOTFIX 2026-04-22: removed 'strict-dynamic'. When that keyword is present,
    // browsers supporting CSP Level 3 *ignore* 'self' and 'https:' — the only
    // trusted scripts are those carrying the nonce attribute. Our middleware
    // sets the nonce in an `x-csp-nonce` header, but Next.js auto-generates its
    // <script src="/_next/static/chunks/*.js" /> tags WITHOUT reading that
    // header (Next.js expects `x-nonce`). The result: every Next.js chunk was
    // blocked in production, the client never hydrated, and the whole site
    // rendered blank shells. Dropping 'strict-dynamic' brings 'self' + 'https:'
    // back into effect so Next.js chunks load from same-origin normally.
    //
    // Long-term proper fix: rename CSP_NONCE_HEADER from 'x-csp-nonce' to
    // 'x-nonce' (Next.js convention). Then Next.js auto-decorates its script
    // tags with the matching nonce and 'strict-dynamic' can come back for
    // stricter XSS protection.
    `script-src 'self' 'nonce-${nonce}' 'unsafe-inline' https:`,

    // Style policy: inline styles retained. Tailwind + Next.js emit inline style
    // attributes/tags that are impractical to nonce today, and the XSS-via-style
    // attack surface (CSS exfiltration) is materially lower than script XSS.
    // Revisit if CSP Level 3 style nonce coverage in Next.js improves.
    `style-src 'self' 'unsafe-inline'`,

    // Image policy: allow same-origin, data URIs, and HTTPS images
    "img-src 'self' data: https:",

    // Font policy: allow same-origin and data URIs (for embedded fonts)
    "font-src 'self' data:",

    // Connect policy: allow API connections to required services
    "connect-src 'self' https://*.supabase.co wss://*.supabase.co https://*.sentry.io https://www.google-analytics.com https://analytics.google.com",

    // Frame ancestors: prevent clickjacking
    "frame-ancestors 'none'",

    // Base URI: prevent base tag hijacking
    "base-uri 'self'",

    // Form actions: only allow forms to submit to same origin
    "form-action 'self'",

    // Object policy: block plugins like Flash
    "object-src 'none'",

    // Upgrade insecure requests in production
    "upgrade-insecure-requests",
  ];

  // Add report-uri if provided
  if (options.reportUri) {
    directives.push(`report-uri ${options.reportUri}`);
  }

  return directives.join('; ');
}

/**
 * Build a development-friendly CSP header
 *
 * This CSP is less restrictive to allow for development tools like
 * Hot Module Replacement (HMR), webpack eval, and React DevTools.
 *
 * WARNING: Do not use this in production!
 *
 * @param nonce - The cryptographic nonce for this request
 * @returns The development CSP header value
 */
export function buildDevCspHeader(nonce: string): string {
  const directives = [
    "default-src 'self'",
    // Allow eval for webpack HMR and development tools
    `script-src 'self' 'nonce-${nonce}' 'unsafe-eval'`,
    // Allow unsafe-inline for HMR style injection in development
    `style-src 'self' 'unsafe-inline'`,
    "img-src 'self' data: https: blob:",
    "font-src 'self' data:",
    "connect-src 'self' https://*.supabase.co wss://*.supabase.co https://*.sentry.io https://www.google-analytics.com https://analytics.google.com ws://localhost:* ws://127.0.0.1:*",
    "frame-ancestors 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "object-src 'none'",
  ];

  return directives.join('; ');
}
